name: ci

on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RACK_ENV: test
      PGSQL_USER: pizza
      PGSQL_DB: pizza
      PGSQL_PW: pizza

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: pizza
          POSTGRES_DB: pizza_test
          POSTGRES_PASSWORD: pizza
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache RVM, Ruby and Bundler
      id: ruby-cache
      uses: actions/cache@v1
      with:
        path: ~/.rvm
        key: ruby-${{ hashFiles('**/.ruby-version') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Set up Ruby from .ruby-version
      if: steps.ruby-cache.outputs.cache-hit != 'true'
      run: |
        curl -sSL https://get.rvm.io | bash
        source $HOME/.rvm/scripts/rvm
        rvm install "$(cat .ruby-version)"
        rvm --default use "$(cat .ruby-version)"

    - name: Cache gems
      id: bundler-cache
      uses: actions/cache@v1
      with:
        path: pizza-api/vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: Bundler setup
      run: |
        source $HOME/.rvm/scripts/rvm
        gem install bundler:1.17.3
        bundle config path pizza-api/vendor/bundle
        bundle _1.17.3_ install --clean --jobs 4 --retry 3

    - name: Setup test database
      env:
        RACK_ENV: test
      run: |
        source $HOME/.rvm/scripts/rvm
        bundle exec rake db:create

    - name: Run tests
      run: |
        source $HOME/.rvm/scripts/rvm
        bundle exec rspec spec
